# Generated by Django 4.2.6 on 2023-10-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('required_elements', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('time_to_cook', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receiptstep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cooking.receiptstep')),
            ],
            bases=('cooking.receiptstep',),
        ),
        migrations.CreateModel(
            name='StepsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_queue', models.PositiveSmallIntegerField(default=1)),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_step', to='cooking.receiptstep')),
                ('from_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_reciept', to='cooking.receipt')),
            ],
            options={
                'unique_together': {('from_receipt', 'position_in_queue')},
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='steps', through='cooking.StepsQueue', to='cooking.receiptstep'),
        ),
    ]
